export const JWT_CONSTANTS = {
  JWT_SECRET_KEY: 'JWT_SECRET',
  JWT_REFRESH_SECRET_KEY: 'JWT_REFRESH_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
} as const;

export const AUTH_CONSTANTS = {
  LOCAL_STRATEGY: 'local',
  JWT_STRATEGY: 'jwt',
  JWT_REFRESH_STRATEGY: 'jwt-refresh',
} as const;